/* CVS $Id: $ */
 
import org.apache.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from stroke_v2.owl 
 * @author Auto-generated by schemagen on 25 fev 2017 20:43 
 */
public class Stroke_v2 {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static final Model M_MODEL = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     * @return namespace as String
     * @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = M_MODEL.createResource( NS );
    
    public static final Resource _drinks_per_week = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#1-6_drinks_per_week" );
    
    public static final Resource _or_2_times_per_week = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#1_or_2_times_per_week" );
    
    public static final Resource _or_more_times_per_week = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#3_or_more_times_per_week" );
    
    public static final Resource _or_more_drinks_per_week = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#7_or_more_drinks_per_week" );
    
    public static final Resource Abstain = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Abstain" );
    
    public static final Resource Accelerometer = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Accelerometer" );
    
    public static final Resource Active = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Active" );
    
    public static final Resource Adverb = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Adverb" );
    
    public static final Resource Alcohol_consuption = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Alcohol_consuption" );
    
    public static final Resource Ambient_light_sensor = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Ambient_light_sensor" );
    
    public static final Resource Barometer = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Barometer" );
    
    public static final Resource College_diploma = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#College_diploma" );
    
    public static final Resource Congestive_heart_failure = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Congestive_heart_failure" );
    
    public static final Resource Critical_of_others = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Critical_of_others" );
    
    public static final Resource Cry_easily = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Cry_easily" );
    
    public static final Resource Device = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Device" );
    
    public static final Resource Diabetes = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Diabetes" );
    
    public static final Resource Drinker = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Drinker" );
    
    public static final Resource Drinks_per_week = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Drinks_per_week" );
    
    public static final Resource Education = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Education" );
    
    public static final Resource Fearful = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Fearful" );
    
    public static final Resource Female = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Female" );
    
    public static final Resource Fingerprint_sensor = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Fingerprint_sensor" );
    
    public static final Resource Former_alcoholic = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Former_alcoholic" );
    
    public static final Resource Former_smoker = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Former_smoker" );
    
    public static final Resource Frequency = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Frequency" );
    
    public static final Resource Gyroscope = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Gyroscope" );
    
    public static final Resource Heart_disease = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Heart_disease" );
    
    public static final Resource Heart_rate_sensor = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Heart_rate_sensor" );
    
    public static final Resource High_school_diploma_and_some_college = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#High-school_diploma_and_some_college" );
    
    public static final Resource Hypertension = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Hypertension" );
    
    public static final Resource Inactive = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Inactive" );
    
    public static final Resource Ischemic_heart_disease = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Ischemic_heart_disease" );
    
    public static final Resource Location_sensor = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Location_sensor" );
    
    public static final Resource Login = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Login" );
    
    public static final Resource Male = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Male" );
    
    public static final Resource Mobile_device = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Mobile_device" );
    
    public static final Resource Never_smoked = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Never_smoked" );
    
    public static final Resource No_high_school_diploma = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#No_high-school_diploma" );
    
    public static final Resource Often_or_always = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Often_or_always" );
    
    public static final Resource Peripheral_arterial_disease = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Peripheral_arterial_disease" );
    
    public static final Resource Person = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Person" );
    
    public static final Resource Physical_activity = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Physical_activity" );
    
    public static final Resource Proximity_sensor = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Proximity_sensor" );
    
    public static final Resource Psychosocial_factors = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Psychosocial_factors" );
    
    public static final Resource Renal_disease = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Renal_disease" );
    
    public static final Resource RiskFactor = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#RiskFactor" );
    
    public static final Resource Sensor = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Sensor" );
    
    public static final Resource Sex = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Sex" );
    
    public static final Resource Smoker = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Smoker" );
    
    public static final Resource Smoking_status = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Smoking_status" );
    
    public static final Resource Sometimes_or_never = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Sometimes_or_never" );
    
    public static final Resource Times_per_week = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Times_per_week" );
    
    public static final Resource Wearable = M_MODEL.createResource( "http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Wearable" );
    
}
