package com.lucas.stroke.v3;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Drinker <br>
 * @version generated on Sun Mar 05 19:13:36 BRT 2017 by dossluca
 */

public interface Drinker extends Alcohol_consumption {

    /* ***************************************************
     * Property http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#hasDrinkPerWeekFrequency
     */
     
    /**
     * Gets all property values for the hasDrinkPerWeekFrequency property.<p>
     * 
     * @returns a collection of values for the hasDrinkPerWeekFrequency property.
     */
    Collection<? extends Drinks_per_week> getHasDrinkPerWeekFrequency();

    /**
     * Checks if the class has a hasDrinkPerWeekFrequency property value.<p>
     * 
     * @return true if there is a hasDrinkPerWeekFrequency property value.
     */
    boolean hasHasDrinkPerWeekFrequency();

    /**
     * Adds a hasDrinkPerWeekFrequency property value.<p>
     * 
     * @param newHasDrinkPerWeekFrequency the hasDrinkPerWeekFrequency property value to be added
     */
    void addHasDrinkPerWeekFrequency(Drinks_per_week newHasDrinkPerWeekFrequency);

    /**
     * Removes a hasDrinkPerWeekFrequency property value.<p>
     * 
     * @param oldHasDrinkPerWeekFrequency the hasDrinkPerWeekFrequency property value to be removed.
     */
    void removeHasDrinkPerWeekFrequency(Drinks_per_week oldHasDrinkPerWeekFrequency);


    /* ***************************************************
     * Property http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#hasFrequency
     */
     
    /**
     * Gets all property values for the hasFrequency property.<p>
     * 
     * @returns a collection of values for the hasFrequency property.
     */
    Collection<? extends WrappedIndividual> getHasFrequency();

    /**
     * Checks if the class has a hasFrequency property value.<p>
     * 
     * @return true if there is a hasFrequency property value.
     */
    boolean hasHasFrequency();

    /**
     * Adds a hasFrequency property value.<p>
     * 
     * @param newHasFrequency the hasFrequency property value to be added
     */
    void addHasFrequency(WrappedIndividual newHasFrequency);

    /**
     * Removes a hasFrequency property value.<p>
     * 
     * @param oldHasFrequency the hasFrequency property value to be removed.
     */
    void removeHasFrequency(WrappedIndividual oldHasFrequency);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
