package com.lucas.stroke.v3;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Login <br>
 * @version generated on Sun Mar 05 19:13:36 BRT 2017 by dossluca
 */

public interface Login extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#hasUserName
     */
     
    /**
     * Gets all property values for the hasUserName property.<p>
     * 
     * @returns a collection of values for the hasUserName property.
     */
    Collection<? extends String> getHasUserName();

    /**
     * Checks if the class has a hasUserName property value.<p>
     * 
     * @return true if there is a hasUserName property value.
     */
    boolean hasHasUserName();

    /**
     * Adds a hasUserName property value.<p>
     * 
     * @param newHasUserName the hasUserName property value to be added
     */
    void addHasUserName(String newHasUserName);

    /**
     * Removes a hasUserName property value.<p>
     * 
     * @param oldHasUserName the hasUserName property value to be removed.
     */
    void removeHasUserName(String oldHasUserName);



    /* ***************************************************
     * Property http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#hasUserPassword
     */
     
    /**
     * Gets all property values for the hasUserPassword property.<p>
     * 
     * @returns a collection of values for the hasUserPassword property.
     */
    Collection<? extends String> getHasUserPassword();

    /**
     * Checks if the class has a hasUserPassword property value.<p>
     * 
     * @return true if there is a hasUserPassword property value.
     */
    boolean hasHasUserPassword();

    /**
     * Adds a hasUserPassword property value.<p>
     * 
     * @param newHasUserPassword the hasUserPassword property value to be added
     */
    void addHasUserPassword(String newHasUserPassword);

    /**
     * Removes a hasUserPassword property value.<p>
     * 
     * @param oldHasUserPassword the hasUserPassword property value to be removed.
     */
    void removeHasUserPassword(String oldHasUserPassword);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
