package com.lucas.stroke.v3;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Sun Mar 05 19:13:36 BRT 2017 by dossluca
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Abstain
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ABSTAIN.<p>
     * 
     */
    public static final OWLClass CLASS_ABSTAIN = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Abstain"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Accelerometer
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ACCELEROMETER.<p>
     * 
     */
    public static final OWLClass CLASS_ACCELEROMETER = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Accelerometer"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Active
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ACTIVE.<p>
     * 
     */
    public static final OWLClass CLASS_ACTIVE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Active"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Adverb
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ADVERB.<p>
     * 
     */
    public static final OWLClass CLASS_ADVERB = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Adverb"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Alcohol_consumption
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ALCOHOL_CONSUMPTION.<p>
     * 
     */
    public static final OWLClass CLASS_ALCOHOL_CONSUMPTION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Alcohol_consumption"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Ambient_light_sensor
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class AMBIENT_LIGHT_SENSOR.<p>
     * 
     */
    public static final OWLClass CLASS_AMBIENT_LIGHT_SENSOR = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Ambient_light_sensor"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Barometer
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BAROMETER.<p>
     * 
     */
    public static final OWLClass CLASS_BAROMETER = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Barometer"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#College_diploma
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COLLEGE_DIPLOMA.<p>
     * 
     */
    public static final OWLClass CLASS_COLLEGE_DIPLOMA = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#College_diploma"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Congestive_heart_failure
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONGESTIVE_HEART_FAILURE.<p>
     * 
     */
    public static final OWLClass CLASS_CONGESTIVE_HEART_FAILURE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Congestive_heart_failure"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Critical_of_others
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CRITICAL_OF_OTHERS.<p>
     * 
     */
    public static final OWLClass CLASS_CRITICAL_OF_OTHERS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Critical_of_others"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Cry_easily
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CRY_EASILY.<p>
     * 
     */
    public static final OWLClass CLASS_CRY_EASILY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Cry_easily"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Device
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DEVICE.<p>
     * 
     */
    public static final OWLClass CLASS_DEVICE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Device"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Diabetes
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DIABETES.<p>
     * 
     */
    public static final OWLClass CLASS_DIABETES = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Diabetes"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Drinker
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DRINKER.<p>
     * 
     */
    public static final OWLClass CLASS_DRINKER = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Drinker"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Drinks_per_week
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DRINKS_PER_WEEK.<p>
     * 
     */
    public static final OWLClass CLASS_DRINKS_PER_WEEK = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Drinks_per_week"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Education
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class EDUCATION.<p>
     * 
     */
    public static final OWLClass CLASS_EDUCATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Education"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Fearful
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FEARFUL.<p>
     * 
     */
    public static final OWLClass CLASS_FEARFUL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Fearful"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Female
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FEMALE.<p>
     * 
     */
    public static final OWLClass CLASS_FEMALE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Female"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Fingerprint_sensor
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FINGERPRINT_SENSOR.<p>
     * 
     */
    public static final OWLClass CLASS_FINGERPRINT_SENSOR = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Fingerprint_sensor"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Former_alcoholic
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FORMER_ALCOHOLIC.<p>
     * 
     */
    public static final OWLClass CLASS_FORMER_ALCOHOLIC = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Former_alcoholic"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Former_smoker
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FORMER_SMOKER.<p>
     * 
     */
    public static final OWLClass CLASS_FORMER_SMOKER = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Former_smoker"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Frequency
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FREQUENCY.<p>
     * 
     */
    public static final OWLClass CLASS_FREQUENCY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Frequency"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Gyroscope
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GYROSCOPE.<p>
     * 
     */
    public static final OWLClass CLASS_GYROSCOPE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Gyroscope"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Heart_disease
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HEART_DISEASE.<p>
     * 
     */
    public static final OWLClass CLASS_HEART_DISEASE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Heart_disease"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Heart_rate_sensor
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HEART_RATE_SENSOR.<p>
     * 
     */
    public static final OWLClass CLASS_HEART_RATE_SENSOR = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Heart_rate_sensor"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#High_school_diploma_and_some_college
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HIGH_SCHOOL_DIPLOMA_AND_SOME_COLLEGE.<p>
     * 
     */
    public static final OWLClass CLASS_HIGH_SCHOOL_DIPLOMA_AND_SOME_COLLEGE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#High_school_diploma_and_some_college"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Hypertension
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HYPERTENSION.<p>
     * 
     */
    public static final OWLClass CLASS_HYPERTENSION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Hypertension"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Inactive
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class INACTIVE.<p>
     * 
     */
    public static final OWLClass CLASS_INACTIVE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Inactive"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Ischemic_heart_disease
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ISCHEMIC_HEART_DISEASE.<p>
     * 
     */
    public static final OWLClass CLASS_ISCHEMIC_HEART_DISEASE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Ischemic_heart_disease"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Location_sensor
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LOCATION_SENSOR.<p>
     * 
     */
    public static final OWLClass CLASS_LOCATION_SENSOR = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Location_sensor"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Login
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LOGIN.<p>
     * 
     */
    public static final OWLClass CLASS_LOGIN = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Login"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Male
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MALE.<p>
     * 
     */
    public static final OWLClass CLASS_MALE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Male"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Mobile_device
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MOBILE_DEVICE.<p>
     * 
     */
    public static final OWLClass CLASS_MOBILE_DEVICE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Mobile_device"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Never_smoked
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NEVER_SMOKED.<p>
     * 
     */
    public static final OWLClass CLASS_NEVER_SMOKED = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Never_smoked"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#No_high_school_diploma
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NO_HIGH_SCHOOL_DIPLOMA.<p>
     * 
     */
    public static final OWLClass CLASS_NO_HIGH_SCHOOL_DIPLOMA = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#No_high_school_diploma"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Often_or_always
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OFTEN_OR_ALWAYS.<p>
     * 
     */
    public static final OWLClass CLASS_OFTEN_OR_ALWAYS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Often_or_always"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#One_or_two_times_per_week
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ONE_OR_TWO_TIMES_PER_WEEK.<p>
     * 
     */
    public static final OWLClass CLASS_ONE_OR_TWO_TIMES_PER_WEEK = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#One_or_two_times_per_week"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#One_to_six_drinks_per_week
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ONE_TO_SIX_DRINKS_PER_WEEK.<p>
     * 
     */
    public static final OWLClass CLASS_ONE_TO_SIX_DRINKS_PER_WEEK = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#One_to_six_drinks_per_week"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Peripheral_arterial_disease
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PERIPHERAL_ARTERIAL_DISEASE.<p>
     * 
     */
    public static final OWLClass CLASS_PERIPHERAL_ARTERIAL_DISEASE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Peripheral_arterial_disease"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Person
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PERSON.<p>
     * 
     */
    public static final OWLClass CLASS_PERSON = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Person"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Physical_activity
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PHYSICAL_ACTIVITY.<p>
     * 
     */
    public static final OWLClass CLASS_PHYSICAL_ACTIVITY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Physical_activity"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Proximity_sensor
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROXIMITY_SENSOR.<p>
     * 
     */
    public static final OWLClass CLASS_PROXIMITY_SENSOR = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Proximity_sensor"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Psychosocial_factors
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PSYCHOSOCIAL_FACTORS.<p>
     * 
     */
    public static final OWLClass CLASS_PSYCHOSOCIAL_FACTORS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Psychosocial_factors"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Renal_disease
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RENAL_DISEASE.<p>
     * 
     */
    public static final OWLClass CLASS_RENAL_DISEASE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Renal_disease"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#RiskFactor
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RISKFACTOR.<p>
     * 
     */
    public static final OWLClass CLASS_RISKFACTOR = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#RiskFactor"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Sensor
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SENSOR.<p>
     * 
     */
    public static final OWLClass CLASS_SENSOR = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Sensor"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Seven_or_more_drinks_per_week
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SEVEN_OR_MORE_DRINKS_PER_WEEK.<p>
     * 
     */
    public static final OWLClass CLASS_SEVEN_OR_MORE_DRINKS_PER_WEEK = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Seven_or_more_drinks_per_week"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Sex
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SEX.<p>
     * 
     */
    public static final OWLClass CLASS_SEX = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Sex"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Smoker
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SMOKER.<p>
     * 
     */
    public static final OWLClass CLASS_SMOKER = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Smoker"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Smoking_status
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SMOKING_STATUS.<p>
     * 
     */
    public static final OWLClass CLASS_SMOKING_STATUS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Smoking_status"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Sometimes_or_never
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SOMETIMES_OR_NEVER.<p>
     * 
     */
    public static final OWLClass CLASS_SOMETIMES_OR_NEVER = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Sometimes_or_never"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Thing
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class THING.<p>
     * 
     */
    public static final OWLClass CLASS_THING = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Thing"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Three_or_more_times_per_week
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class THREE_OR_MORE_TIMES_PER_WEEK.<p>
     * 
     */
    public static final OWLClass CLASS_THREE_OR_MORE_TIMES_PER_WEEK = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Three_or_more_times_per_week"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Times_per_week
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TIMES_PER_WEEK.<p>
     * 
     */
    public static final OWLClass CLASS_TIMES_PER_WEEK = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Times_per_week"));

    /* ***************************************************
     * Class http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Wearable
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class WEARABLE.<p>
     * 
     */
    public static final OWLClass CLASS_WEARABLE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#Wearable"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#hasAdverbFrequency
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASADVERBFREQUENCY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASADVERBFREQUENCY = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#hasAdverbFrequency"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#hasDevice
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASDEVICE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASDEVICE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#hasDevice"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#hasDrinkPerWeekFrequency
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASDRINKPERWEEKFREQUENCY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASDRINKPERWEEKFREQUENCY = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#hasDrinkPerWeekFrequency"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#hasEducation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASEDUCATION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASEDUCATION = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#hasEducation"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#hasFrequency
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASFREQUENCY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASFREQUENCY = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#hasFrequency"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#hasLogin
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASLOGIN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASLOGIN = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#hasLogin"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#hasRiskFactor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASRISKFACTOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASRISKFACTOR = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#hasRiskFactor"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#hasSensor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASSENSOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASSENSOR = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#hasSensor"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#hasSex
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASSEX.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASSEX = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#hasSex"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#hasTimesPerWeekFrequency
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASTIMESPERWEEKFREQUENCY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASTIMESPERWEEKFREQUENCY = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#hasTimesPerWeekFrequency"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#topObjectProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWL:TOPOBJECTPROPERTY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWL = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#topObjectProperty"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#hasAge
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASAGE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASAGE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#hasAge"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#hasName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASNAME = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#hasName"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#hasRiskLevel
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASRISKLEVEL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASRISKLEVEL = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#hasRiskLevel"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#hasUserName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASUSERNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASUSERNAME = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#hasUserName"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#hasUserPassword
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASUSERPASSWORD.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASUSERPASSWORD = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/lucas/ontologies/2016/9/stroke#hasUserPassword"));

    /* ***************************************************
     * Data Property http://www.w3.org/2002/07/owl#topDataProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property OWL:TOPDATAPROPERTY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_OWL = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2002/07/owl#topDataProperty"));


}
